### ISSUE TITLE
Write a proper documentation of how to use this tool for VSIX unit tests

### ISSUE THREAD

**Issue by Enache-Ionut** [josetr/VsixTesting#24]

**Comment by josetr** [comment]
Sorry about that. I have updated the main README file which should make things a bit more clear now. It also includes a link to a repo containing fully working samples: `https://github.com/josetr/VsixTestingSamples`.

If this is not enough and you are still having problems with a specific subject please let me know.

**Comment by Enache-Ionut** [comment]
Unfortunately, it still doesn't work. I checked on another machine and the sample project works fine but is not the case on my machine. The Experimental instance of Visual Studio begins to run but suddenly closes.

Here is the output log:

[4/1/2019 4:36:36 PM Informational] ------ Run test started ------
[4/1/2019 4:36:36 PM Informational] [xUnit.net 00:00:00.3722532]   Discovering: VsClassLibrary.Tests
[4/1/2019 4:36:36 PM Informational] [xUnit.net 00:00:00.4899349]   Discovered:  VsClassLibrary.Tests
[4/1/2019 4:36:36 PM Informational] [xUnit.net 00:00:00.4927082]   Starting:    VsClassLibrary.Tests
[4/1/2019 4:36:40 PM Error] [xUnit.net 00:00:04.0623611]     VsClassLibrary.Tests.DteUtilitiesTests.TestMethod15 - 2017 Exp [FAIL]
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0632084]       System.IO.FileNotFoundException : Could not load file or assembly 'file:///D:\xUnit%20test\VsClassLibrary\VsClassLibrary.Tests\bin\Debug\net461\VsixTesting.DLL' or one of its dependencies. The system cannot find the file specified.
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0638327]       Stack Trace:
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0643644]            at object RuntimeType.ForwardCallToInvokeMember(string memberName, BindingFlags flags, object target, int[] aWrapperTypes, ref MessageData msgData)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0644133]            at object VsixTesting.Remoting.IRemoteComInvoker.InvokeMethod(string assemblyPath, string class, string method, object obj, object[] arguments)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0644986]         C:/projects/vsixtesting/src/VsixTesting/VsInstance.cs(155,0): at object VsixTesting.VsInstance.InvokeRemote(IRemoteComInvoker comInvoker, string method, object[] arguments)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0645526]         C:/projects/vsixtesting/src/VsixTesting/VsInstance.cs(92,0): at void VsixTesting.VsInstance+<>c__DisplayClass16_0+<<Launch>b__0>d.MoveNext()
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0646041]            at void VsixTesting.XunitX.Internal.DiagnosticTestRunner<T>+<>c__DisplayClass5_0+<<RunAsync>b__0>d.MoveNext()
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0646480]         C:/Dev/xunit/xunit/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs(48,0): at async Task Xunit.Sdk.ExecutionTimer.AggregateAsync(Func<Task> asyncAction)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0646935]         C:/projects/vsixtesting/src/VsixTesting.Xunit/Internal/Diagnostics.cs(180,0): at async Task<decimal> VsixTesting.XunitX.Internal.DiagnosticTestRunner<T>.RunAsync(IMessageBus messageBus, CancellationTokenSource cancellationTokenSource)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0647405]         C:/projects/vsixtesting/src/VsixTesting.Xunit/Internal/VsInstanceTestAssemblyRunner.cs(111,0): at async Task VsixTesting.XunitX.Internal.VsInstanceTestAssemblyRunner.Init(CancellationTokenSource cts)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0647854]         C:/projects/vsixtesting/src/VsixTesting.Xunit/Internal/VsInstanceTestAssemblyRunner.cs(79,0): at async Task<RunSummary> VsixTesting.XunitX.Internal.VsInstanceTestAssemblyRunner.RunAsync(CancellationTokenSource cts)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0651905]       Output:
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0652303]         1. Preparing Instance
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0652603]         Extension VsixTesting.Invoker 1.0.0 is up to date.
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0652888]         
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0653435]         2. Launching Instance
[4/1/2019 4:36:40 PM Error] [xUnit.net 00:00:04.0680276]     2. Launching Instance [FAIL]
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0681382]       System.IO.FileNotFoundException : Could not load file or assembly 'file:///D:\xUnit%20test\VsClassLibrary\VsClassLibrary.Tests\bin\Debug\net461\VsixTesting.DLL' or one of its dependencies. The system cannot find the file specified.
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0682857]       Stack Trace:
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0683595]            at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0684150]            at VsixTesting.Remoting.IRemoteComInvoker.InvokeMethod(String assemblyPath, String class, String method, Object obj, Object[] arguments)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0684777]         C:\projects\vsixtesting\src\VsixTesting\VsInstance.cs(155,0): at VsixTesting.VsInstance.InvokeRemote(IRemoteComInvoker comInvoker, String method, Object[] arguments)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0685415]         C:\projects\vsixtesting\src\VsixTesting\VsInstance.cs(92,0): at VsixTesting.VsInstance.<>c__DisplayClass16_0.<<Launch>b__0>d.MoveNext()
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0685765]         --- End of stack trace from previous location where exception was thrown ---
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0686164]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0686554]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0686946]            at VsixTesting.XunitX.Internal.DiagnosticTestRunner`1.<>c__DisplayClass5_0.<<RunAsync>b__0>d.MoveNext()
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0687348]         --- End of stack trace from previous location where exception was thrown ---
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0687723]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0688176]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0688533]         --- End of stack trace from previous location where exception was thrown ---
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0688975]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0689379]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0689857]         C:\projects\vsixtesting\src\VsixTesting.Xunit\Internal\Diagnostics.cs(180,0): at VsixTesting.XunitX.Internal.DiagnosticTestRunner`1.<RunAsync>d__5.MoveNext()
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0690162]         --- End of stack trace from previous location where exception was thrown ---
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0690564]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0690957]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0691525]         C:\projects\vsixtesting\src\VsixTesting.Xunit\Internal\VsInstanceTestAssemblyRunner.cs(111,0): at VsixTesting.XunitX.Internal.VsInstanceTestAssemblyRunner.<Init>d__41.MoveNext()
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0691751]         --- End of stack trace from previous location where exception was thrown ---
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0692186]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0692630]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0693102]         C:\projects\vsixtesting\src\VsixTesting.Xunit\Internal\VsInstanceTestAssemblyRunner.cs(79,0): at VsixTesting.XunitX.Internal.VsInstanceTestAssemblyRunner.<RunAsync>d__40.MoveNext()
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0693441]         --- End of stack trace from previous location where exception was thrown ---
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0693908]         C:\projects\vsixtesting\src\VsixTesting.Xunit\Internal\VsInstanceTestAssemblyRunner.cs(88,0): at VsixTesting.XunitX.Internal.VsInstanceTestAssemblyRunner.<RunAsync>d__40.MoveNext()
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0694323]         --- End of stack trace from previous location where exception was thrown ---
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0694753]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0695131]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0695502]         C:\projects\vsixtesting\src\VsixTesting.Xunit\Internal\VsTestAssemblyRunner.cs(59,0): at VsixTesting.XunitX.Internal.VsTestAssemblyRunner.<>c__DisplayClass7_0.<<Remote_RunTestCasesAsync>b__2>d.MoveNext()
[4/1/2019 4:36:40 PM Informational] [xUnit.net 00:00:04.0735614]   Finished:    VsClassLibrary.Tests
[4/1/2019 4:36:40 PM Informational] ========== Run test finished: 2 run (0:00:04.4724801) ==========

**Comment by josetr** [comment]
Possible solutions
* Upgrade VsixTesting.Xunit package to 1.1.49-beta
* Remove bin/obj files completly
* Ensure VsixTesting.dll actually exists in the `VsClassLibrary.Tests` bin folder
* Compare the bin folders from both machines and see they have the same asssemblies
* Clone this repo and see if the simple test `ClassFixtureTests.Fact` works
* If you get the same error
    * Set a breakpoint at https://github.com/josetr/VsixTesting/blob/8feffa31d5046b49362223dfbe55639d08098fa4/src/VsixTesting.Invoker/InvokerService.cs#L12
    * Debug the test, check the `assemblyPath` variable and see if the path exists

Apparently Windows 10 can handle case sensitive files so if you have enabled it by any chance, disable it.

**Comment by Enache-Ionut** [comment]
I upgrade to 1.1.49-beta and everything is working fine. Thank you for all your help.
