### ISSUE TITLE
Skip installation if the extension is already installed globally

### ISSUE THREAD

**Issue by tgeng** [josetr/VsixTesting#27]
Hi, first thank you for this awesome library. This makes it so much easier for us to set up integration test for our Visual Studio extension.

In our testing setup, we have already installed the plugin globally for other tests with admin elevation (since we need to install outside of the extension). In such cases tests are failing with the following error:

```
Error Message:
 System.Exception : System.Exception: Extension 'MyPlugin 1.0' version must be higher than the globally installed extension 'MyPlugin 1.0'.
   at VsixTesting.Installer.Installer.Install(String extensionPath, Nullable`1 allUsers)
   at VsixTesting.Installer.Installer.<>c__DisplayClass5_1.<Install>b__0(String path)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at VsixTesting.Installer.Installer.Install(String applicationPath, String rootSuffix, IEnumerable`1 extensionPaths, Nullable`1 allUsers)
   at VsixTesting.Installer.Program.<>c__DisplayClass1_0.<Run>b__0()
   at VsixTesting.Installer.Program.Run(String applicationPath, String rootSuffix, String[] args)
Stack Trace:
   at async Task<(int Result, string Output)> Vs.VisualStudioUtil.RunInstallerAsync(VsHive hive, IEnumerable<string> args)
   at async Task<(int InstallCount, string Output)> Vs.VisualStudioUtil.InstallExtensionsAsync(VsHive hive, IEnumerable<string> extensions)
   at void VsixTesting.VsInstance+<>c__DisplayClass15_0+<<Prepare>b__0>d.MoveNext()
   at void VsixTesting.IDiagnosticsExtensions+<>c__DisplayClass1_0+<<RunAsync>b__0>d.MoveNext()
   at void VsixTesting.XunitX.Internal.DiagnosticTestRunner<T>+<>c__DisplayClass5_0+<<RunAsync>b__0>d.MoveNext()
   at async Task Xunit.Sdk.ExecutionTimer.AggregateAsync(Func<Task> asyncAction)
   at async Task<decimal> VsixTesting.XunitX.Internal.DiagnosticTestRunner<T>.RunAsync(IMessageBus messageBus, CancellationTokenSource cancellationTokenSource)
   at async Task VsixTesting.VsInstance.Prepare(VsHive hive, IEnumerable<string> extensionsToInstall, bool resetSettings, IDiagnostics diagnostics, bool installInvoker)
   at async Task VsixTesting.XunitX.Internal.VsInstanceTestAssemblyRunner.Init(CancellationTokenSource cts)
   at async Task<RunSummary> VsixTesting.XunitX.Internal.VsInstanceTestAssemblyRunner.RunAsync(CancellationTokenSource cts)
```
It would be great if we can just make the test to proceed in such case since the extension is already installed.

**Comment by tgeng** [comment]
While looking at the Program.cs under installer, it seems that the installer by default should not install an extension if it's already installed. I am suspecting [this line](https://github.com/josetr/VsixTesting/blob/master/src/VsixTesting.Installer/Program.cs#L280) is the culprit. Does the `IsUpToDate` logic work regarding extensions that are installed for all users?

**Comment by sharwell** [comment]
💭 Extensions can be installed for the experimental instance even if another copy of the extension is installed globally. We rely on this behavior for testing extensions that ship with Visual Studio, such as the C# language service. I would agree that we can skip installation for extensions already installed, but only in cases where the existing installation is an _exact content match_, and not just a version match.

**Comment by tgeng** [comment]
Thanks Sam. That makes sense. We could manually uninstall before the test run and let it reinstall as well. But that would fail with the following error

```
Error Message:
 System.Exception : System.InvalidOperationException: Unable to install files outside of extension directory when installing per-user.
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.ValidatePackage(VsixPackage vsixPackage, String installDir, Boolean installPerMachine, String sourceFile)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.Validate(ZipPackage packageContainer)
   at Microsoft.VisualStudio.ExtensionManager.DefaultPackageInstaller.Validate(ZipPackage packageContainer)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Install(IInstallableExtension extension, InstallFlags installFlags, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.Install(IInstallableExtension extension, Boolean perMachine)
   at VsixTesting.Installer.Installer.Install(String extensionPath, Nullable`1 allUsers)
   at VsixTesting.Installer.Installer.<>c__DisplayClass5_1.<Install>b__0(String path)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at VsixTesting.Installer.Installer.Install(String applicationPath, String rootSuffix, IEnumerable`1 extensionPaths, Nullable`1 allUsers)
   at VsixTesting.Installer.Program.<>c__DisplayClass1_0.<Run>b__0()
   at VsixTesting.Installer.Program.Run(String applicationPath, String rootSuffix, String[] args)
```

Is there a way to make it through?

**Comment by josetr** [comment]
If the extension is already installed and it's actually the version you want to test then simply stop VsixTesting from trying to install it again by using `<ProjectReference Include="MyPlugin.csproj"  CopyVsix="false" />`.

**Comment by tgeng** [comment]
Awesome! CopyVsix="false" works great for us. Thank you!
