### ISSUE TITLE
Newtonsoft.Json dependency fails after VS 2022 17.2 update

### ISSUE THREAD

**Issue by emrekultursay** [josetr/VsixTesting#35]
The `VsixTesting.Installer.x64.exe` tries to load `Newtonsoft.Json` version 9.0, but with Visual Studio 2022, the minimum version of `Newtonsoft.Json` is 13.0 (https://devblogs.microsoft.com/visualstudio/using-newtonsoft-json-in-a-visual-studio-extension/)

This incorrect dependency started causing test failures with a recent Visual Studio 2022 17.2 update. With that update, the `Newtonsoft.Json.dll` (9.0.0) file located at `Common\Ide\PrivateAssemblies\` was deleted, and this dependency is no longer (accidentally) satisfied.

```
  Error Message:
   System.Exception : System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.VisualStudio.Setup.Serialization.PackageSerializer..ctor(IServiceProvider services)
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.GetVsixType(Stream vsixStream)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.Microsoft.VisualStudio.ExtensionManager.IVsExtensionManager.CreateInstallableExtension(String extensionPath)
   at VsixTesting.Installer.Installer.Install(String extensionPath, Nullable`1 allUsers)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at VsixTesting.Installer.Installer.Install(String applicationPath, String rootSuffix, IEnumerable`1 extensionPaths, Nullable`1 allUsers)
   at VsixTesting.Installer.Program.Run(String applicationPath, String rootSuffix, Version vsProductVersion, String[] args)

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  c:\src\temp\5ou1evhk.avg\VsixTesting.Installer.x64.exe
--- A detailed error log follows.

=== Pre-bind state information ===
LOG: DisplayName = Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
 (Fully-specified)
LOG: Appbase = file:///c:/src/temp/5ou1evhk.avg
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.VisualStudio.Setup.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: No application configuration file found.
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
LOG: Attempting download of new URL file:///c:/src/temp/5ou1evhk.avg/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///c:/src/temp/5ou1evhk.avg/Newtonsoft.Json/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///c:/src/temp/5ou1evhk.avg/Newtonsoft.Json.EXE.
LOG: Attempting download of new URL file:///c:/src/temp/5ou1evhk.avg/Newtonsoft.Json/Newtonsoft.Json.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/PrivateAssemblies/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/PrivateAssemblies/Newtonsoft.Json/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/PrivateAssemblies/Newtonsoft.Json.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/PrivateAssemblies/Newtonsoft.Json/Newtonsoft.Json.EXE.

  Stack Trace:
     at async Task<(int Result, string Output)> Vs.VisualStudioUtil.RunInstallerAsync(VsHive hive, IEnumerable<string> args) in D:/a/VsixTesting/VsixTesting/src/VsixTesting/Vs/VisualStudioUtil.Installer.cs:line 51
   at async Task<(int InstallCount, string Output)> Vs.VisualStudioUtil.InstallExtensionsAsync(VsHive hive, IEnumerable<string> extensions) in D:/a/VsixTesting/VsixTesting/src/VsixTesting/Vs/VisualStudioUtil.Installer.cs:line 18
   at void VsixTesting.VsInstance+<>c__DisplayClass15_0+<<Prepare>b__0>d.MoveNext() in D:/a/VsixTesting/VsixTesting/src/VsixTesting/VsInstance.cs:line 53
   at void VsixTesting.IDiagnosticsExtensions+<>c__DisplayClass1_0+<<RunAsync>b__0>d.MoveNext() in D:/a/VsixTesting/VsixTesting/src/VsixTesting/IDiagnostics.cs:line 34
   at void VsixTesting.XunitX.Internal.DiagnosticTestRunner<T>+<>c__DisplayClass5_0+<<RunAsync>b__0>d.MoveNext() in D:/a/VsixTesting/VsixTesting/src/VsixTesting.Xunit/Internal/Diagnostics.cs:line 182
   at async Task Xunit.Sdk.ExecutionTimer.AggregateAsync(Func<Task> asyncAction) in C:/Dev/xunit/xunit/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at async Task<decimal> VsixTesting.XunitX.Internal.DiagnosticTestRunner<T>.RunAsync(IMessageBus messageBus, CancellationTokenSource cancellationTokenSource) in D:/a/VsixTesting/VsixTesting/src/VsixTesting.Xunit/Internal/Diagnostics.cs:line 185
   at async Task VsixTesting.VsInstance.Prepare(VsHive hive, IEnumerable<string> extensionsToInstall, bool resetSettings, IDiagnostics diagnostics, bool installInvoker) in D:/a/VsixTesting/VsixTesting/src/VsixTesting/VsInstance.cs:line 41
   at async Task VsixTesting.XunitX.Internal.VsInstanceTestAssemblyRunner.Init(CancellationTokenSource cts) in D:/a/VsixTesting/VsixTesting/src/VsixTesting.Xunit/Internal/VsInstanceTestAssemblyRunner.cs:line 111
   at async Task<RunSummary> VsixTesting.XunitX.Internal.VsInstanceTestAssemblyRunner.RunAsync(CancellationTokenSource cts) in D:/a/VsixTesting/VsixTesting/src/VsixTesting.Xunit/Internal/VsInstanceTestAssemblyRunner.cs:line 80
```

**Comment by josetr** [comment]
I've fixed the issue and published a new version on nuget.org.

Thanks for reporting the issue 👍
