### ISSUE TITLE
Newtonsoft.Json dependency fails on VS 2022 17.4

### ISSUE THREAD

**Issue by Sedeniono** [josetr/VsixTesting#36]
I am currently on VS 2022 17.4.2 and running the tests fails. 
I.e. cloning https://github.com/josetr/VsixTestingSamples, opening one of the two sample solutions, building everything and attempting to run a VS 2022 test fails.
Test explorer says:
```
Message: 
System.Exception : System.IO.FileNotFoundException: Could not load file or assembly "Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" or one of its dependencies. The system cannot find the file specified.
File name: "Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"
   at Microsoft.VisualStudio.Setup.Serialization.PackageSerializer..ctor(IServiceProvider services)
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.GetVsixType(Stream vsixStream)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.Microsoft.VisualStudio.ExtensionManager.IVsExtensionManager.CreateInstallableExtension(String extensionPath)
   at VsixTesting.Installer.Installer.Install(String extensionPath, Nullable`1 allUsers)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at VsixTesting.Installer.Installer.Install(String applicationPath, String rootSuffix, IEnumerable`1 extensionPaths, Nullable`1 allUsers)
   at VsixTesting.Installer.Program.Run(String applicationPath, String rootSuffix, Version vsProductVersion, String[] args)

=== Pre-bind state information ===
LOG: DisplayName = Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
 (Fully-specified)
LOG: Appbase = file:///C:/Users/<User>/AppData/Local/Temp/ig3g2ple.kis
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.VisualStudio.Setup.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: No application configuration file found.
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config wird verwendet.
LOG: Post-policy reference: Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
LOG: Attempting download of new URL file:///C:/Users/<User>/AppData/Local/Temp/ig3g2ple.kis/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Users/<User>/AppData/Local/Temp/ig3g2ple.kis/Newtonsoft.Json/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Users/<User>/AppData/Local/Temp/ig3g2ple.kis/Newtonsoft.Json.EXE.
LOG: Attempting download of new URL file:///C:/Users/<User>/AppData/Local/Temp/ig3g2ple.kis/Newtonsoft.Json/Newtonsoft.Json.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/PrivateAssemblies/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/PrivateAssemblies/Newtonsoft.Json/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/PrivateAssemblies/Newtonsoft.Json.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/PrivateAssemblies/Newtonsoft.Json/Newtonsoft.Json.EXE.


  Stack Trace: 
VisualStudioUtil.RunInstallerAsync(VsHive hive, IEnumerable<string> args) line 51
VisualStudioUtil.InstallExtensionsAsync(VsHive hive, IEnumerable<string> extensions) line 18
VsInstance+<>c__DisplayClass15_0+<<Prepare>b__0>d.MoveNext() line 55
IDiagnosticsExtensions+<>c__DisplayClass1_0+<<RunAsync>b__0>d.MoveNext() line 34
VsInstance.Prepare(VsHive hive, IEnumerable<string> extensionsToInstall, bool resetSettings, IDiagnostics diagnostics, bool installInvoker) line 41
VsInstanceTestAssemblyRunner.Init(CancellationTokenSource cts) line 111
VsInstanceTestAssemblyRunner.RunAsync(CancellationTokenSource cts) line 80

  Standard Output: 
1. Preparing Instance
```
(Some parts were originally in German; I translated them to English.)

I can see that I have a `C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PrivateAssemblies\Newtonsoft.Json.13.0.1.0\`, but no `13.0.0.0`.

I guess this is more or less the same issue as with the 17.2 update that was reported in issue #35?

**Comment by Sedeniono** [comment]
The issue appeared because the samples at https://github.com/josetr/VsixTestingSamples and also the readme of this repository here does not reference the latest package version (0.1.75) but instead an older version. I missed that at first. Updating to the newer version fixes the Newtonsoft.JSON problem.
