### ISSUE TITLE
Nerdbank.Streams error on Visual Studio 2022 after update to 17.7.4

### ISSUE THREAD

**Issue by emrekultursay** [josetr/VsixTesting#38]
VsixTesting stopped working somewhere between VS versions 17.5 - 17.7. Currently, the latest Visual Studio version is 17.7.4, and the `VsixTesting.Instances.VisualStudio.VisualStudio[2022Exp]`  test (using the sample with version upgraded to 0.1.75) fails with the following error:

```
Message: 
System.Exception : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Nerdbank.Streams, Version=2.9.0.0, Culture=neutral, PublicKeyToken=cac503e1823ce71c' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.VisualStudio.ExtensionEngine.Impl.Settings.MetadataStore.ExtensionMetadataStore.ReadExtensionData(IEngineHost engineHost)
   at Microsoft.VisualStudio.ExtensionManager.Impl.Settings.ExtensionSettingsCache.LoadExtensionMetadata()
   at Microsoft.VisualStudio.ExtensionManager.Impl.Settings.ExtensionSettingsCache..ctor(ISettingsManager settingsManager, IEngineHost engineHost, IExtensionEngine engine)
   at Microsoft.VisualStudio.ExtensionManager.Impl.Settings.InstalledExtensionSettingsList..ctor(IEngineHost engineHost, IExtensionEngine engine, IExtensionSettingsCache extensionSettingsCache)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl..ctor(IEngineHost engineHost, EngineMode mode, IEnumerable`1 enabledExtensions, CancellationToken disposalToken, IExtensionSettingsCache extensionSettingsCache)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService..ctor(ISettingsManager settingsManager, CultureInfo preferredCulture, ExtensionManagerServiceMode mode, IEnumerable`1 enabledExtensions, EngineHostId engineHostId, CancellationToken disposalToken, Boolean delayServiceHub, ILogger logger, IExtensionSettingsCache extensionSettingsCache)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService..ctor(SettingsManager settings, ExtensionManagerServiceMode mode, ILogger logger)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at VsixTesting.Installer.ExtensionManagerService.Create(ExternalSettingsManager externalSettingsManager)
   at VsixTesting.Installer.Installer.Install(String applicationPath, String rootSuffix, IEnumerable`1 extensionPaths, Nullable`1 allUsers)
   at VsixTesting.Installer.Program.Run(String applicationPath, String rootSuffix, Version vsProductVersion, String[] args)

  Stack Trace: 
<RunInstallerAsync>d__17.MoveNext() line 51
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<InstallExtensionsAsync>d__15.MoveNext() line 18
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<<Prepare>b__0>d.MoveNext() line 55
--- End of stack trace from previous location where exception was thrown ---
<16 more frames...>
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<Prepare>d__15.MoveNext() line 41
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<<LaunchAndDebug>b__0>d.MoveNext() line 73
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<<RunOnStaThreadAsync>b__0>d.MoveNext() line 43

  (result has additional output)
```

The library `Nerdbank.Streams` is available at `C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PublicAssemblies\Nerdbank.Streams.2.x\Nerdbank.Streams.dll`, but it's not picked up. From the error, it looks like it's trying to load version 2.9.0, but that file in Visual Studio version has been updated from 2.8.0 to 2.10.0, which might be the reason for the issue. Maybe it's an assembly redirect problem (not sure on VsixTesting or Visual Studio)?

**Comment by josetr** [comment]
Fixed on https://www.nuget.org/packages/VsixTesting.Xunit/0.1.78
